src/Entity/Commentaires.php
<?php

namespace App\Entity;

use App\Repository\CommentairesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentairesRepository::class)]
class Commentaires
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $contenu;

    #[ORM\Column(type: 'string', length: 30)]
    private $Pseudo;

    #[ORM\Column(type: 'date', nullable: true)]
    private $date_commentaire;


 

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    public function getDateCommentaire(): ?\DateTimeInterface
    {
        return $this->date_commentaire;
    }

    public function setDateCommentaire(?\DateTimeInterface $date_commentaire): self
    {
        $this->date_commentaire = $date_commentaire;

        return $this;
    }

}

src/Controller/AdminCommentairesController.php
<?php

namespace App\Controller;

use App\Entity\Commentaires;
use App\Form\CommentairesType;
use App\Repository\CommentairesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/commentaires')]
class AdminCommentairesController extends AbstractController
{
    #[Route('/', name: 'app_admin_commentaires_index', methods: ['GET'])]
    public function index(CommentairesRepository $commentairesRepository): Response
    {
        return $this->render('admin_commentaires/index.html.twig', [
            'commentaires' => $commentairesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_commentaires_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CommentairesRepository $commentairesRepository): Response
    {
        $commentaire = new Commentaires();
        $form = $this->createForm(CommentairesType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentairesRepository->add($commentaire);
            return $this->redirectToRoute('app_admin_commentaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_commentaires/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_commentaires_show', methods: ['GET'])]
    public function show(Commentaires $commentaire): Response
    {
        return $this->render('admin_commentaires/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_commentaires_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentaires $commentaire, CommentairesRepository $commentairesRepository): Response
    {
        $form = $this->createForm(CommentairesType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commentairesRepository->add($commentaire);
            return $this->redirectToRoute('app_admin_commentaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_commentaires/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_commentaires_delete', methods: ['POST'])]
    public function delete(Request $request, Commentaires $commentaire, CommentairesRepository $commentairesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $commentairesRepository->remove($commentaire);
        }

        return $this->redirectToRoute('app_admin_commentaires_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/admin_commentaires/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_commentaires_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
<button style="margin-left:20px" class="btn btn-danger">Supprimer</button>

</form>

templates/admin_commentaires/_form.html.twig
<div class="coments">
{{ form_start(form) }}
    {{ form_widget(form) }}
<button style="margin-left:20px" class="btn btn-dark">{{ button_label|default('Enregistrer') }}</button>

{{ form_end(form) }}
</div>

templates/admin_commentaires/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Commentaires{% endblock %}

{% block body %}
    <h1>Edit Commentaires</h1>

    {{ include('admin_commentaires/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_commentaires_index') }}">back to list</a>

    {{ include('admin_commentaires/_delete_form.html.twig') }}
{% endblock %}

templates/admin_commentaires/index.html.twig
{% extends 'adminBase.html.twig' %}


{% block title %}Commentaires index{% endblock %}

{% block body %}
    <h1>Commentaires </h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Contenu</th>
                <th>Pseudo</th>
                <th>Date_commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.contenu }}</td>
                <td>{{ commentaire.Pseudo }}</td>
                <td>{{ commentaire.dateCommentaire ? commentaire.dateCommentaire|date('Y-m-d') : '' }}</td>
                <td>
                    <a class="btn btn-dark"href="{{ path('app_admin_commentaires_show', {'id': commentaire.id}) }}">Voir</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a style="margin-left:20px"class="btn btn-dark" href="{{ path('app_admin_commentaires_new') }}">Ajouter un commentaire</a>
{% endblock %}

templates/admin_commentaires/new.html.twig
{% extends 'adminBase.html.twig' %}


{% block title %} Commentaires{% endblock %}

{% block body %}
    <h1>Ajout Commentaire</h1>

    {{ include('admin_commentaires/_form.html.twig') }}

  <a style="margin-left:20px"class="btn badge-dark" href="{{ path('app_admin_commentaires_index') }}">Retour à la liste</a>

{% endblock %}

templates/admin_commentaires/show.html.twig
{% extends 'adminBase.html.twig' %}


{% block title %}Commentaires{% endblock %}

{% block body %}
    <h1>Commentaires</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ commentaire.contenu }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ commentaire.Pseudo }}</td>
            </tr>
            <tr>
                <th>Date_commentaire</th>
                <td>{{ commentaire.dateCommentaire ? commentaire.dateCommentaire|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

<a style="margin-left:20px;margin-bottom:25px" class="btn btn-light" href="{{ path('app_admin_commentaires_index') }}">Retour à la liste</a>

    {{ include('admin_commentaires/_delete_form.html.twig') }}
{% endblock %}